import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Navbar } from "@/components/navbar";
import { BottomNav } from "@/components/bottom-nav";

// Quick wrapper to use client component
const NavbarWrapper = () => {
  return (
    <>
      <div className="hidden md:block">
        <Navbar />
      </div>
      <div className="md:hidden">
        <Navbar />
      </div>
      <BottomNav />
    </>
  )
}
// Wait, Top Navbar usually stays on Mobile too for User Profile / Bell.
// But the LINKS inside Navbar should be hidden on mobile.
// I will update Navbar to hide links on mobile.
// And use BottomNav for navigation.


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex min-h-screen flex-col">
            {/* Navbar is strictly inside Providers because it uses useSession */}
            <NavbarWrapper />
            <main className="flex-1">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
